hide_cursor = true
ignore_empty_input = true
fail_timeout = 1000

background {
  color = rgba(101419ff)
  blur_passes = 3
}

input-field {
  outline_thickness = 5
  outer_color = rgba(70a5ebff)
  inner_color = rgba(13171cff)
  font_color = rgba(b6becaff)
  font_family = JetBrainsMono Nerd Font Mono
  placeholder_text = password
  rounding = 15
  check_color = rgba(78dba9ff)
  check_text = checking
  fail_color = rgba(e05f65ff)
  fail_text = <i>incorrect. <b>($ATTEMPTS)</b></i>
  fade_on_empty = true
}
