
$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus
$menu = wofi --show drun
$browser = firefox
$server = $HOME/minecraft-server/start.sh
$ai = opencode
$logout = $HOME/.config/waybar/powermenu.sh
# quick commands

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, ESCAPE, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod SHIFT, F, exec, $fileManager
bind = $mainMod, T, togglefloating
bind = $mainMod, SPACE, exec, $menu
bind = $mainMod SHIFT, RETURN, exec, $browser
bind = $mainMod SHIFT, S, exec, sh $server
bind = $mainMod SHIFT, Q, exec, $logout
bind = $mainMod SHIFt, C, exec, $ai

# switching focus

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u

# workspaces

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# screenshots

bind = $mainMod CTRL, W, exec, hyprshot -m window --clipboard-only
bind = $mainMod CTRL, S, exec, hyprshot -m region --clipboard-only
bind = $mainMod CTRL SHIFT, W, exec, hyprshot -m window
bind = $mainMod CTRL SHIFT, S, exec, hyprshot -m region

# volume

bind = $mainMod, 123, exec, pactl set-sink-volume 0 +5%
bind = $mainMod, 122, exec, pactl set-sink-volume 0 -5%
bind = $mainMod, 121, exec, amixer set Master 0%

# playback

bind = $mainMod, 172, exec, playerctl play-pause
bind = $mainMod, 173, exec, playerctl previous
bind = $mainMod, 171, exec, playerctl next

# windows

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# niceness

general {
    border_size = 3
    col.active_border = rgba(70a5ebff)
    col.inactive_border = rgba(485263ff)
}

animations {
  enabled = yes
}

misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  background_color = rgba(101419ff)
}

decoration {
    active_opacity = 0.95
    inactive_opacity = 0.85
    rounding = 15

}

# stuff to startup

exec-once = waybar
exec-once = swaync
exec-once = hyprpaper
# exec-once = swaybg -i /home/alstocras/dotfiles/wallpaper.png
exec-once = hypridle

# locking

bind = $mainMod SHIFT, L, exec, hyprlock

