-- Generated by hyprconf2lua v1.3.2
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mainMod = "SUPER"

local terminal = "kitty"

local fileManager = "nautilus"

local menu = "wofi --show drun"

local browser = "firefox"

local server = "local_var_HOME/minecraft-server/start.sh"

local ai = "opencode"

local logout = "local_var_HOME/.config/waybar/powermenu.sh"

-- quick commands

hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(
	mainMod .. " + " .. "ESCAPE",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit")
)

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.exec_cmd("nautilus"))

hl.bind(mainMod .. " + " .. "T", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.exec_cmd("wofi --show drun"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "RETURN", hl.dsp.exec_cmd("firefox"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("sh local_var_HOME/minecraft-server/start.sh"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.exec_cmd(logout))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "C", hl.dsp.exec_cmd("opencode"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "A", hl.dsp.exec_cmd("fastfetch"))

-- switching focus

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

-- workspaces

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

-- workspace moving

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

-- screenshots

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "W", hl.dsp.exec_cmd("hyprshot -m window --clipboard-only"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "S", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("hyprshot -m window"))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("hyprshot -m region"))

-- volume

-- hl.bind(mainMod .. " + " .. 123, hl.dsp.exec_cmd("pactl set-sink-volume 0 +5%"))

-- hl.bind(mainMod .. " + " .. 122, hl.dsp.exec_cmd("pactl set-sink-volume 0 -5%"))

-- hl.bind(mainMod .. " + " .. 121, hl.dsp.exec_cmd("amixer set Master 0%"))

-- playback

hl.bind(mainMod .. " + code:172", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind(mainMod .. " + code:173", hl.dsp.exec_cmd("playerctl previous"))

hl.bind(mainMod .. " + code:171", hl.dsp.exec_cmd("playerctl next"))

-- windows

--[[
hl.window_rule({
    name  = "float_on",
    match = {
        match = "class org.pulseaudio.pavucontrol",
    },
    -- TODO: review rule: "float on"
})
]]

-- hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

-- hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- niceness

-- TODO: manual review: icon-theme = "Papirus-Dark"

hl.config({
	general = {
		gaps_in = 4,
		gaps_out = 4,
		border_size = 3,
		col = {
			active_border = "rgba(70a5ebff)",
			inactive_border = "rgba(485263ff)",
		},
	},
})

hl.config({
	animations = {
		enabled = true,
	},
})

hl.config({
	misc = {
		force_default_wallpaper = 0,
		disable_hyprland_logo = true,
		background_color = "rgba(101419ff)",
	},
})

hl.config({
	decoration = {
		active_opacity = 0.99,
		inactive_opacity = 0.85,
		rounding = 15,
	},
})

-- stuff to startup

-- exec-once = swaybg -i /home/alstocras/dotfiles/wallpaper.png

-- locking

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

-- keyboard

hl.config({
	input = {
		kb_layout = "us,ru",
		kb_variant = ",phonetic",
		kb_options = "grp:alt_shift_toggle,caps:escape",
	},
})

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("waybar")
	hl.exec_cmd("swaync")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hypridle")
end)
