; COLOR EXPLANATION
; main, sidebar, player = background
; card                  = cards, tracklist, dropdowns, input fields
; shadow                = text on button, tab active & selected row
; selected row          = selected song & tab
; button-active         = play button, outline on focused input
; button                = all other buttons
; button-disabled       = volume & seekbar background, scrollbar handle, borders, hover

[dark-decay]
text               = b6beca
subtext            = 4d5768
main               = 101419
sidebar            = 101419
player             = 101419
card               = 1a1e23
shadow             = 0e1217
selected-row       = 70a5eb
button             = 70a5eb
button-active      = 70a5eb
button-disabled    = 242931
tab-active         = 70a5eb
notification       = 1a1e23
notification-error = e05f65
misc               = 1a1e23
